[toolchain]
channel = "1.89.0"
package_manager = "npm"

[features]
resolution = true
skip-lint = false

[programs.localnet]
atlas_forge_svm = "5u6WZQsMPrufRZVbnWKjv6K1cH2pmF3gXbVhK15rh1eQ"

[programs.devnet]
atlas_forge_svm = "5u6WZQsMPrufRZVbnWKjv6K1cH2pmF3gXbVhK15rh1eQ"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 \"tests/**/*.ts\""
